---
title: "Book"
author: "Lamy Lionel"
date: "02/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup
```{r}
# ---
# Please see setup.R
# ---

set.seed(122020)
source("./sources/setup.r")
source("./sources/drawing.r")
source("./sources/minimization.r")
source("./sources/investigate.R")

# Global X and Y
CP.X = sort(X(n))
CP.Y = Y(CP.X)
CP.x = seq(0, 1, length = n) 
# # Sorted
# CP.X = sort(CP.X)
# CP.Y = CP.Y[order(CP.X)]

# Kernel
Knorm = function(u) dnorm(u) #Gaussian kernel

# NW Estimator
NW.regEst <- function(x, X, Y, h, K) sum(Y * K((x - X)/h))/sum(K((x - X)/h))
```

# Finding best bandwidth and polynomial order

```{r, echo=F, error=F, warning=F}
# ---
# Please see minimize.R
# ---

# ---
# Warning: might take a while
# Use ni=100, M=100 by default but better results with higher values
# ---

# NW.minimizeMISE(h.test = seq(0.03, 0.05, 0.001), M=500)

NW.optimal = NW.minimizeMSSE(h.test = seq(0.03, 0.05, 0.001), M=500)
LM.optimal = LM.minimizeMSSE(M=500)

# Optimal bandwidth
NW.h = NW.optimal$h[1] # 0.036
# Optimal degree
LM.poly = LM.optimal$poly[1] # 7

# Models (for futur use)

NW.optimal.model = sapply(seq(0,1,length=nrow(NW.optimal)), function(x) NW.regEst(x, CP.X, CP.Y, NW.h, Knorm))
LM.optimal.model = lm(CP.Y ~ poly(CP.X, LM.poly))$fitted
```

## Investigation of the optimal model
### Bias, Variance and MSSE

```{r}
# As X.optimal already contains the bias and the MSSE
# we only need to compute the variance, via MReg

NW.optimal$variance = round(
  mean((NW.optimal.model - NW.optimal$MReg)^2)
,4)

LM.optimal$variance = round(
  mean((LM.optimal.model - LM.optimal$MReg)^2)
,4)

# head(NW.optimal, 1)
# head(LM.optimal, 1)
```

## Investigation at interesting points
### Of the MSE

```{r}
# ---
# Please see investigate.R
# ---

CP.to_check = c(0,0.2,0.45,0.63,0.78,0.91,1) 
CP.investigation.samples = c(25,50,100,200,400,600,800,1000) # smoother lines 

# Draw which points
plot(CP.X, CP.Y, pch="+", col = "grey", xlab = "x", ylab="Y")
lines(CP.x, m(CP.x), col = 1, lwd=2)
abline(v=CP.to_check, col=2, lty=3)
title("Interesting points to investigate")
legend("topleft", 
    legend = c("True"),
    col = c(1),
    lty = c(1),
    cex = 1.5
)

# Compute all the MSE
NW.investigation.results = CP.investigation.toframe(NW.investigation)
LM.investigation.results = CP.investigation.toframe(LM.investigation)
```

# Some plots 

```{r}
# ---
# Please see drawing.R
# ---

# ---
# Draw the evolution of MSE
CP.drawMSE(NW.investigation.results, "MSE evolution for NW", save=T)
CP.drawMSE(LM.investigation.results, "MSE evolution for LM", save=T)

# ---
# Plot both LM and NW best regression
CP.drawComparison(NW.optimal$MReg, LM.optimal$MReg, 100, save=F)

# ===

# ---
# Plot the bias alone

jpeg("./plots/bias/NW-Alone.jpg", quality = 100, width = 1080, height = 720)
plot(CP.x, NW.optimal$Bias, col=2, lwd=2, lty=1,type="l", xlab = "x", ylab="Bias", main="NW-Bias evolution")
abline(h=0, col=1, lty=3)
dev.off()

jpeg("./plots/bias/LM-Alone.jpg", quality = 100, width = 1080, height = 720)
plot(CP.x, LM.optimal$Bias, col=4, lwd=2, lty=1, type="l", xlab = "x", ylab="Bias", main="LM-Bias evolution")
abline(h=0, col=1, lty=3)
dev.off()

# Both in the same time
jpeg("./plots/bias/NW-LM-Alone.jpg", quality = 100, width = 1080, height = 720)
plot(CP.x, NW.optimal$Bias, col=2, lwd=2, lty=1,type="l", xlab = "x", ylab="Bias", main="NW & LM Bias evolution")
lines(CP.x, LM.optimal$Bias, col=4, lwd=2, lty=1)
abline(h=0, col=1, lty=3)
legend("topleft", 
   legend = c("True", "NW Bias", "LM Bias"),
   col = c(1, 2, 4),
   lty = c(1, 1, 1),
   cex = 1.5
)
dev.off()

# ---
# Plot bias and regression

jpeg("./plots/bias/NW-Both.jpg", quality = 100, width = 1080, height = 720)
plot(CP.X, CP.Y, pch="+", col = "grey", xlab = "x", ylab="Y", main="NW and Bias")
lines(CP.x, m(CP.x), col = 1, lwd=2)
lines(CP.x, NW.optimal$MReg, col=2, lty=1, lwd=2) 
lines(CP.x, NW.optimal$Bias, col=6, lty=2)
abline(h=0, col=1, lty=3)
legend("topleft", 
   legend = c("True", "NW Regression", "NW Bias"),
   col = c(1, 2, 6),
   lty = c(1, 1, 2),
   cex = 1.5
)
dev.off()

jpeg("./plots/bias/LM-Both.jpg", quality = 100, width = 1080, height = 720)
plot(CP.X, CP.Y, pch="+", col = "grey", xlab = "x", ylab="Y", main="LM and Bias")
lines(CP.x, m(CP.x), col = 1, lwd=2)
lines(CP.x, LM.optimal$MReg, col=4, lty=1, lwd=2)
lines(CP.x, LM.optimal$Bias, col=5, lty=2)
abline(h=0, col=1, lty=3)
legend("topleft", 
   legend = c("True", "LM Regression", "LM Bias"),
   col = c(1, 4, 5),
   lty = c(1, 1, 2),
   cex = 1.5
)
dev.off()
```

# =====
#  END
# =====

# Plotting and comparison
```{r}

for(p in 1:20){

  jpeg(paste0("./plots/LM-Line-100-Boot/",p,".jpg"), quality = 100, width = 1080, height = 720)
  plot(CP.X, CP.Y, pch="+", col = "grey", xlab = "x", ylab="Y", main=paste0("Polynomial regression with degree=",p))
  lines(CP.X, lm(CP.Y ~ poly(CP.X, degree = p))$fitted, lwd=2, col=4)
  lines(CP.x, m(CP.x), col = 1, lwd=2)
  legend("topleft", 
     legend = c("True", "Regression"),
     col = c(1, 4),
     lty = c(1, 1),
     cex = 1.5
  )
  dev.off()
}

```


```{r}
# ndpConf = predict(ndp, interval = "conf")
plot(X, Y, pch="+", col = "grey")
# lines(x, ndpConf[,2], type = "l", col = 1)
lines(x, predict(smooth.spline(X, Y, cv = 3, spar = 0.6))$y, type = "l", col = 1, lwd=1.5)
lines(x, ndp$fitted, type = "l", col = 4, lwd=1.5)
# lines(x, ndpConf[,3], type = "l", col = 1)
lines(x, NWnormEst, type = "l", col = 2, lwd=1.5)
lines(x, m(x), type = "l", col = 3, lwd=1.5)
legend("topleft", 
  legend = c("LR", "NW", "True"),
  col = c(4, 2, 3),
  lty = c(1, 1, 1, 1), cex = 0.5)
```

